version: '3.9'

services:
  db:
    image: postgres:14
    container_name: a4tunados_postgres
    restart: always
    environment:
      POSTGRES_DB: a4tunados
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: majorssolutions/a4tunados-backend:latest
    container_name: a4tunados_backend
    command: >
      sh -c "sleep 5 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    working_dir: /app
    ports:
      - "8081:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    restart: always

volumes:
  postgres_data:
